### ISSUE TITLE
Fatal Error: redirectToRoute() not found

### ISSUE THREAD

**Issue by INSEAD-asim** [lightSAML/SpBundle#18]
Hi,

I am implementing sp-bundle in Symfony 2.3 project. It appears that this function was implemented in Symfony 2.6. Can you help?

> FatalErrorException: Error: Call to undefined method LightSaml\SpBundle\Controller\DefaultController::redirectToRoute() in C:\DATA\Projects\PHP\Symfony2\Symfony2-LightSAML-SP\vendor\lightsaml\sp-bundle\src\LightSaml\SpBundle\Controller\DefaultController.php line 47

**Comment by tmilos** [comment]
Sorry about that, I missed it. In [DefaultController](https://github.com/lightSAML/SpBundle/blob/master/src/LightSaml/SpBundle/Controller/DefaultController.php) lines using ``$this->redirectToRoute`` should be modified to use a Symfony 2.3 compatible way of redirection/creating path.

**Comment by kidatsy** [comment]
I ran into the same thing and dropping this here for anyone else who runs across it. The override was pretty simple. There are instructions here for overriding vendor bundles: http://symfony.com/doc/2.7/bundles/override.html

Since the basic setup for LightsamlSPBundle involves extending Entities, defining new Services anyway, might as well make a new Bundle that extends the base lightsaml Bundle, as outlined above.

Replace `return $this->redirectToRoute(...` with `return $this->redirect($this->generateUrl(` in `discoveryAction` and `loginAction`.

Also make sure to copy over the `Resources/config/routing.yml` to your new bundle and point the routes for those two actions to your new controller's actions, and you should be set.

**Comment by tmilos** [comment]
Why wouldn't you make a pull request?

**Comment by kidatsy** [comment]
I did the override in the name of expediency, but can make a PR, too!

**Comment by kidatsy** [comment]
Here's the PR: https://github.com/lightSAML/SpBundle/pull/37

**Comment by tmilos** [comment]
Merged #37 and released with 1.0.5. Thanks for the PR
