### ISSUE TITLE
Question: Custom redirect URL after successfull login

### ISSUE THREAD

**Issue by berny46** [lightSAML/SpBundle#48]
Hi everyone,
is it possible to redirect the User to a different URL than the one he initially came from? Let's say User is on example.com/shop, clicked on example.com/login, get's redirected to my IDP and I want to redirect him back to example.com/shop after successfull login.

Edit: To clarify what I'd like to do: 
When using simplesamlphp you can do something like that:

`$auth->requireAuth(array(
    'ReturnTo' => 'https://sp.example.org/mycustompath'
));`
@tmilos Any Idea?

Thanks
Chris

Edit: [Question on stackoverflow](https://stackoverflow.com/questions/44408287/custom-redirect-url-after-successfull-saml-login)

**Comment by tmilos** [comment]
This is a standard Symfony feature. You should use ``default_target_path`` security listener configuration option. It's not listed on [LightSAML Sp Bundle configuration](https://www.lightsaml.com/SP-Bundle/Configuration/) since it's a standard Symfony option, though I might add it to avoid the confusion.
